// Code generated by MockGen. DO NOT EDIT.
// Source: ./grpc.go

// Package mock_exchanger_grpc is a generated GoMock package.
package mock_exchanger_grpc

import (
	context "context"
	reflect "reflect"

	exchangev1 "github.com/Njrctr/gw-proto-exchange/gen/go/exchange"
	gomock "github.com/golang/mock/gomock"
)

// MockGRPCApi is a mock of GRPCApi interface.
type MockGRPCApi struct {
	ctrl     *gomock.Controller
	recorder *MockGRPCApiMockRecorder
}

// MockGRPCApiMockRecorder is the mock recorder for MockGRPCApi.
type MockGRPCApiMockRecorder struct {
	mock *MockGRPCApi
}

// NewMockGRPCApi creates a new mock instance.
func NewMockGRPCApi(ctrl *gomock.Controller) *MockGRPCApi {
	mock := &MockGRPCApi{ctrl: ctrl}
	mock.recorder = &MockGRPCApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGRPCApi) EXPECT() *MockGRPCApiMockRecorder {
	return m.recorder
}

// GetExchangeRateForCurrency mocks base method.
func (m *MockGRPCApi) GetExchangeRateForCurrency(ctx context.Context, from, to string) (exchangev1.ExchangeRateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExchangeRateForCurrency", ctx, from, to)
	ret0, _ := ret[0].(exchangev1.ExchangeRateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExchangeRateForCurrency indicates an expected call of GetExchangeRateForCurrency.
func (mr *MockGRPCApiMockRecorder) GetExchangeRateForCurrency(ctx, from, to interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExchangeRateForCurrency", reflect.TypeOf((*MockGRPCApi)(nil).GetExchangeRateForCurrency), ctx, from, to)
}

// GetExchangeRates mocks base method.
func (m *MockGRPCApi) GetExchangeRates(ctx context.Context) (exchangev1.ExchangeRatesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExchangeRates", ctx)
	ret0, _ := ret[0].(exchangev1.ExchangeRatesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExchangeRates indicates an expected call of GetExchangeRates.
func (mr *MockGRPCApiMockRecorder) GetExchangeRates(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExchangeRates", reflect.TypeOf((*MockGRPCApi)(nil).GetExchangeRates), ctx)
}
